# Markdownlint – canonical config for XXXChatNow
default: true
MD013: false  # line length
MD033: false  # inline HTML
MD041: false  # first line heading
MD024:
  allow_different_nesting: true
MD034: false  # bare URL used
MD040: false  # fenced code blocks should have a language
MD026: false  # trailing punctuation in heading
