# Canonical. Do not duplicate or override except by DECISIONS.md approval.
# Markdown linting rules for Super-Linter

default: true

# MD013: Line length - disabled to allow long lines in code blocks and tables
MD013: false

# MD024: Multiple headings with same content - allow if nesting differs
MD024:
  allow_different_nesting: true

# MD026: Trailing punctuation in heading - disabled for flexibility
MD026: false

# MD033: Inline HTML - disabled to allow HTML in markdown
MD033: false

# MD034: Bare URL used - disabled to allow plain URLs
MD034: false

# MD040: Fenced code blocks should have a language - disabled for flexibility
MD040: false

# MD041: First line in file should be a top-level heading - disabled
MD041: false
