default: true
MD013: false   # line length
MD033: false   # inline HTML
MD041: false   # first line heading
# Markdown linting rules
# Using minimal configuration for Super-Linter compliance

# Line length - allow long lines for code blocks and tables
MD013: false

# Multiple headings with same content
MD024:
  allow_different_nesting: true

# Inline HTML
MD033: false

# Bare URL used
MD034: false

# First line in file should be a top-level heading
MD041: false

# Fenced code blocks should have a language specified
MD040: false

# Trailing punctuation in heading
MD026: false
