---
# YAML linting rules
# Using minimal configuration for Super-Linter compliance

extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
  comments:
    min-spaces-from-content: 1
