export const PUSH_NOTIFICATION_TOPIC = 'xcams';
export const FIREBASE_SETTING_KEYS = {
  FIREBASE_API_KEY: 'FIREBASE_API_KEY',
  FIREBASE_AUTH_DOMAIN: 'FIREBASE_AUTH_DOMAIN',
  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_STORAGE_BUCKET: 'FIREBASE_STORAGE_BUCKET',
  FIREBASE_MESSAGING_SENDER_ID: 'FIREBASE_MESSAGING_SENDER_ID',
  FIREBASE_APPID: 'FIREBASE_APPID',
  FIREBASE_MEASUREMENT_ID: 'FIREBASE_MEASUREMENT_ID',
  FIREBASE_WEB_PUSH_KEYPAIR: 'FIREBASE_WEB_PUSH_KEYPAIR',
  FIREBASE_CLIENT_EMAIL: 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY: 'FIREBASE_PRIVATE_KEY'
};
